fragment pr on PullRequest { number, title }

# viewerQuery repo:%s state:open is:pr author:%s
# reviewerQuery repo:%s state:open review-requested:%s
query PullRequestStatus($owner: String!, $repo: String!, $headRefName: String!, $viewerQuery: String!, $reviewerQuery: String!, $per_page: Int = 10) {
    repository(owner: $owner, name: $repo) {
        defaultBranchRef {
            name
        }
        pullRequests(headRefName: $headRefName, first: $per_page, orderBy: { field: CREATED_AT, direction: DESC }) {
            totalCount
            edges {
                node {
                    ...pr
                }
            }
        }
    }

    viewerCreated: search(query: $viewerQuery, type: ISSUE, first: $per_page) {
        totalCount: issueCount
        edges {
            node {
                ...pr
            }
        }
    }
    reviewRequested: search(query: $reviewerQuery, type: ISSUE, first: $per_page) {
        totalCount: issueCount
            edges {
                node {
                    ...pr
                }
            }
        }
}