fragment pr on PullRequest { number, title }

query PullRequestStatus($query: String!, $per_page: Int = 10) {
    viewerCreated: search(query: $query, type: ISSUE, first: $per_page) {
        totalCount: issueCount
        edges {
            node {
                ...pr
            }
        }
    }
}