fragment pr on PullRequest { number, title }

query PullRequestStatus($prSearch: String!, $per_page: Int = 10) {
    viewerCreated: search(query: $prSearch, type: ISSUE, first: $per_page) {
        totalCount: issueCount
        edges {
            node {
                ...pr
            }
        }
    }
}